= brpaste(1)
Chloe Kudryavtsev
v0.0.1a
:doctype: manpage

== Name

brpaste - a pastebin service that's so fast, it burns rubber.

== Synopsis

*brpaste* [_OPTIONS_]

== Options

*-b, --bind*=_BIND_ADDRESS_::
    Bind to address _BIND_ADDRESS_. May be used multiple times.
*-p, --port*=_LISTEN_PORT_::
    Listen on port _LISTEN_PORT_.
*-r, --redis*=_REDIS_URI_::
    Connect to Redis using _REDIS_URI_.

== Endpoints

_GET_ */*::
    Index.
    Provides simplified table of this section.
    Provides examples.
    Includes submission form.

_GET_ */:id?(syntax|lang=syntax)*::
    User-facing viewer of paste _id_.
    If javascript is available, attempt to highlight the paste as _syntax_.

_GET_ */raw/:id*::
    Raw contents of paste _id_.
    Mime is set to plaintext.

_POST_ */* _data_=*content*::
    Pastebin *content*.
    The _id_ will be the the base64 representation of content's murmurhash3 hash.
    If that _id_ already exists, it is overwritten.

_PUT_ */:id* _data_=*content*::
    Put *content* into _id_.
    If _id_ already exists, abort.

_GET|REPORT_ */health*::
    Returns 204 is healthy.
    Gives more information in case of failure.

== See Also

https://vibed.org/
