= brpaste(1)
Chloe Kudryavtsev
v2.0.0
:doctype: manpage

== Name

brpaste - a pastebin service that's so fast, it burns rubber.

== Synopsis

*brpaste* [_OPTIONS_]

== Options

*-bind*=_BIND_ADDRESS_::
    Bind to address _BIND_ADDRESS_.
*-redis*=_REDIS_URI_::
    Connect to Redis using _REDIS_URI_.
*-storage*=_STORAGE_SYSTEM_::
    What storage system to use. See valid options in <<_storage_systems>>.

== Endpoints

_GET_ */*::
    Index.
    Provides simplified table of this section.
    Provides examples.
    Includes submission form.

_GET_ */:id*::
    User-facing viewer of paste _id_.
    Standard view.

_GET_ */:id/:syntax*::
    Same as */:id*.
    If javascript is available, attempt to highlight the paste as _syntax_.

_GET_ */:id/raw*::
    Raw contents of paste _id_.
    Mime is set to plaintext.

_POST_ */* _data_=*content*::
    Pastebin *content*.
    The _id_ will be the the base64 representation of content's murmurhash3 hash.
    If that _id_ already exists, it is overwritten.

_PUT_ */:id* _data_=*content*::
    Put *content* into _id_.
    If _id_ already exists, abort.

== Storage Systems

Memory::
Selected with "memory".
Not persistent, but very fast.

Redis::
Selected with "redis".
Also the default and recommended option.
Fast and simple.
