#!/sbin/openrc-run
supervisor=supervise-daemon

healthcheck_timer=30
respawn_delay=30

command=/usr/bin/brpaste
command_args="\
    ${BRPASTE_USER:+--uid $BRPASTE_USER} ${BRPASTE_GROUP:+--gid $BRPASTE_GROUP} \
    ${BRPASTE_REDIS:+-r $BRPASTE_REDIS} \
    ${BRPASTE_IP:+-b $BRPASTE_IP} ${BRPASTE_PORT:+-p $BRPASTE_PORT}"

depend() {
    need redis
}

health() {
    curl -s "${BRPASTE_IP:-localhost}:${BRPASTE_PORT:-8080}/health"
}

unhealthy() {}
